# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_initial_django18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=150, unique=True, verbose_name='email address'),
        ),
    ]
